name: Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install --yes libnetcdf-dev libnetcdf-c++4-dev libnetcdff-dev libudunits2-dev
      - name: Build project
        run: |
          cmake -S . -B .
          cmake --build .
      - name: Run tests
        run: ctest
